hot fix:
- title: 'Add support for alternative data_fusion package name'
  description: 'data_fusion is not an allowed name for the data_fusion package on pypi. We have temporarily pushed it to pypi as geoips_data_fusion. This change allows geoips run to use the pypi packaged version of the data_fusion file.'
  files:
    modified:
    - 'geoips/commandline/geoips_run.py'
  related-issue:
    number: null
    repo_url: ''
  date:
    start: null
    finish: null
